// components/print/PrintLayout.jsx
import React from 'react';
import { useTranslation } from 'react-i18next';

const PrintLayout = ({
  title,
  subtitle,
  data = {},
  children,
  showFooter = true,
  headerContent,
  className = '',
}) => {
  const { t } = useTranslation();

  return (
    <div className={`print-layout ${className}`}>
      {/* Header */}
      <div className="print-header mb-6 p-4 bg-gray-800 text-white rounded">
        <div className="flex justify-between items-start">
          <div>
            <h1 className="text-2xl font-bold mb-2">{title}</h1>
            {subtitle && <p className="text-gray-200">{subtitle}</p>}
            {headerContent && <div className="mt-2">{headerContent}</div>}
          </div>
          <div className="text-right text-sm">
            <p>
              <strong>{t('Generated on')}:</strong>{' '}
              {new Date().toLocaleDateString()}
            </p>
            <p>
              <strong>{t('Time')}:</strong> {new Date().toLocaleTimeString()}
            </p>
          </div>
        </div>

        {/* Data summary */}
        {Object.keys(data).length > 0 && (
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mt-4 text-sm">
            {Object.entries(data).map(([key, value]) => (
              <div key={key}>
                <strong>{t(key)}:</strong> {value}
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Content */}
      <div className="print-content">{children}</div>

      {/* Footer */}
      {showFooter && (
        <div className="mt-8 pt-4 border-t border-gray-300 text-sm text-gray-600">
          <p>
            {t('Generated by Banking System')} - {window.location.origin}
          </p>
          <p>
            {t('Page')} <span className="page-number"></span>
          </p>
        </div>
      )}
    </div>
  );
};

export default PrintLayout;
