import { formatNumber } from './formatNumber';
import { useDateFormatter } from '../hooks/useDateFormatter';

export const generateTransactionPrintHTML = (
  transactions,
  customerInfo,
  accountSummary,
  t,
  formatDisplay
) => {
  const getTransactionDescription = (transaction) => {
    if (transaction.description) {
      return transaction.description;
    }

    switch (transaction.type) {
      case 'deposit':
        return t('Deposit to account');
      case 'withdraw':
        return t('Withdrawal from account');
      case 'transfer':
        return `${transaction.senderName || t('Sender')} → ${
          transaction.receiverName || t('Receiver')
        }`;
      case 'receive':
        return `${transaction.senderName || t('Sender')} → ${
          transaction.receiverName || t('Receiver')
        }`;
      case 'exchange_sale':
        return t('Currency Sale');
      case 'exchange_purchase':
        return t('Currency Purchase');
      default:
        return t('Transaction');
    }
  };

  return `
    <div class="print-header">
      <h1>${t('Transaction History Report')}</h1>
    </div>

    <div class="print-meta">
      <div>
        <strong>${t('Customer')}:</strong> ${customerInfo.name || 'N/A'}<br>
        <strong>${t('Customer ID')}:</strong> ${customerInfo.id || 'N/A'}
      </div>
      <div style="text-align: right;">
        <strong>${t(
          'Print Date'
        )}:</strong> ${new Date().toLocaleDateString()}<br>
        <strong>${t('Total Transactions')}:</strong> ${transactions.length}
      </div>
    </div>

    ${
      accountSummary.length > 0
        ? `
      <div style="margin-bottom: 20px;">
        <h2 style="margin-bottom: 10px; font-size: 18px;">${t(
          'Account Summary'
        )}</h2>
        <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 10px;">
          ${accountSummary
            .map(
              (account) => `
            <div class="summary-card">
              <strong>${t('Account')} ${account.accountNo}</strong><br>
              <span style="font-size: 16px; font-weight: bold; ${
                account.balance < 0 ? 'color: #dc3545;' : 'color: #28a745;'
              }">
                ${formatNumber(account.balance)} ${account.currency}
              </span>
            </div>
          `
            )
            .join('')}
        </div>
      </div>
    `
        : ''
    }

    ${
      transactions.length > 0
        ? `
      <table>
        <thead>
          <tr>
            <th>${t('Transaction ID')}</th>
            <th>${t('Date & Time')}</th>
            <th>${t('Description')}</th>
            <th class="text-right">${t('Debit')}</th>
            <th class="text-right">${t('Credit')}</th>
            <th class="text-center">${t('Currency')}</th>
            <th class="text-right">${t('Balance')}</th>
            <th class="text-center">${t('Type')}</th>
          </tr>
        </thead>
        <tbody>
          ${transactions
            .map(
              (transaction) => `
            <tr>
              <td>${
                transaction.No ||
                transaction.transferNo ||
                transaction.receiveNo ||
                'N/A'
              }</td>
              <td>${formatDisplay(transaction.date, { showTime: true })}</td>
              <td>${getTransactionDescription(transaction)}</td>
              <td class="text-right">${
                transaction.debit > 0 ? formatNumber(transaction.debit) : '-'
              }</td>
              <td class="text-right">${
                transaction.credit > 0 ? formatNumber(transaction.credit) : '-'
              }</td>
              <td class="text-center">${transaction.moneyType || 'N/A'}</td>
              <td class="text-right ${
                transaction.runningBalance < 0 ? 'negative' : 'positive'
              }">
                ${formatNumber(transaction.runningBalance)}
              </td>
              <td class="text-center">
                ${t(
                  transaction.type === 'exchange_sale'
                    ? 'Exchange Sale'
                    : transaction.type === 'exchange_purchase'
                    ? 'Exchange Purchase'
                    : transaction.type
                )}
              </td>
            </tr>
          `
            )
            .join('')}
        </tbody>
      </table>
    `
        : `
      <div style="text-align: center; padding: 40px; color: #6c757d;">
        <h3>${t('No transactions found')}</h3>
        <p>${t('No transaction records available for printing.')}</p>
      </div>
    `
    }

    <div class="print-footer">
      ${t('Generated by Banking System')} • ${
    window.location.hostname
  } • ${new Date().toLocaleString()}
    </div>
  `;
};

export const generateTransferPrintHTML = (transfer, t, formatDisplay) => {
  if (!transfer) {
    return `
      <div style="font-family: 'Courier New', monospace; font-size: 10px; width: 60mm; padding: 5px;">
        <div style="text-align: center; margin-bottom: 10px;">
          <strong>${t('NO TRANSFER DATA')}</strong>
        </div>
      </div>
    `;
  }

  return `
    <div style="font-family: 'Courier New',  monospace; font-size: 10px; width: 60mm; padding: 5px; line-height: 1.2;">
      <div style="text-align: center; margin-bottom: 8px; border-bottom: 1px dashed #000; padding-bottom: 5px;">
        <strong style="font-size: 12px;">${t('Send')}</strong><br>
        <span>${t('RECEIPT')}</span>
      </div>
      <!-- Transfer Info -->
      <div style="margin-bottom: dir:'rtl' 8px;">
        <strong>${t('Number')}:</strong> #${transfer.transferNo || 'N/A'}<br>
        <strong>${t('Date')}:</strong> ${formatDisplay(
    transfer.tDate || new Date(),
    { showTime: true }
  )}<br>
        <strong>${t('Print')}:</strong> ${new Date().toLocaleTimeString()}
      </div>

      <div style="border-top: 1px dashed #000; margin: 5px 0; padding-top: 5px;">
        <strong>${t('Transfer')}:</strong>
        ${transfer.senderName || 'Unknown'}<br>
        ${transfer.senderAccountNo ? `Acc: ${transfer.senderAccountNo}` : ''}
      </div>
      <div style="border-top: 1px dashed #000; margin: 5px 0; padding-top: 5px;">
        <strong>${t('Receiver')}:</strong>
        ${transfer.receiverName || 'Unknown'}<br>
        ${
          transfer.receiverAccountNo ? `Acc: ${transfer.receiverAccountNo}` : ''
        }
      </div>    
      <!-- Amount Details -->
      <div style="border-top: 1px dashed #000;">
        <table style="width: 100%; border-collapse: collapse;">
          <tr>
            <td><strong>${t('Amount')}:</strong></td>
            <td style="text-align: right;">${
              formatNumber(transfer.transferAmount) || '0.00'
            }</td>
            <td style="text-align: center;">${
              transfer.MainMoneyType?.typeName || 'N/A'
            }</td>
          </tr>
          <tr>
            <td><strong>${t('charges')}:</strong></td>
            <td style="text-align: right;">${
              formatNumber(transfer.chargesAmount) || '0.00'
            }</td>
            <td style="text-align: center;">${
              transfer.ChargesMoneyType?.typeName || 'N/A'
            }</td>
          </tr>
          <tr style="border-top: 1px solid #000;">
            <td><strong>${t('TOTAL')}:</strong></td>
            <td style="text-align: right; font-weight: bold;">${formatNumber(
              (transfer.transferAmount || 0) + (transfer.chargesAmount || 0)
            )}</td>
            <td></td>
          </tr>
        </table>
      </div>

      <!-- Description -->
      ${
        transfer.description
          ? `
        <div style="border-top: 1px dashed #000; margin: 5px 0; padding-top: 5px;">
          <strong>${t('Memo')}:</strong>
          ${transfer.description}
        </div>
      `
          : ''
      }

      <!-- Footer -->
      <div style="border-top: 1px dashed #000; margin-top: 8px; padding-top: 5px; text-align: center; font-size: 9px;">
        <div>${t('Thank you for banking with us')}</div>
        <div>${new Date().toLocaleDateString()} • ${t('SENDER COPY')}</div>
        <div style="font-size: 8px; margin-top: 3px;">
          ID: TRF-${transfer.transferNo}
        </div>
      </div>

      <!-- Cut here line -->
      <div style="text-align: center; margin-top: 10px; border-top: 1px dashed #000; padding-top: 5px;">
        ✄ - - - - - - - - - - - - - - - - ✄
      </div>
    </div>
  `;
};

export const generateReceivePrintHTML = (receive, t, formatDisplay) => {
  if (!receive) {
    return `
      <div style="font-family: 'Courier New', monospace; font-size: 10px; width: 60mm; padding: 5px;">
        <div style="text-align: center; margin-bottom: 10px;">
          <strong>${t('NO Receive DATA')}</strong>
        </div>
      </div>
    `;
  }
  return `
    <div style="font-family: 'Courier New',  monospace; font-size: 10px; width: 60mm; padding: 5px; line-height: 1.2;">
      <div style="text-align: center; margin-bottom: 8px; border-bottom: 1px dashed #000; padding-bottom: 5px;">
        <strong style="font-size: 12px;">${t('Receive')}</strong><br>
        <span>${t('RECEIPT')}</span>
      </div>
      <!-- receive Info -->
      <div style="margin-bottom: dir:'rtl' 8px;">
        <strong>${t('Number')}:</strong> #${receive.receiveNo || 'N/A'}<br>
        <strong>${t('Date')}:</strong> ${formatDisplay(
    receive.rDate || new Date(),
    { showTime: true }
  )}<br>
        <strong>${t('Print')}:</strong> ${new Date().toLocaleTimeString()}
      </div>

      <div style="border-top: 1px dashed #000; margin: 5px 0; padding-top: 5px;">
        <strong>${t('Transfer')}:</strong>
        ${receive.senderName || 'Unknown'}<br>
        ${receive.senderAccountNo ? `Acc: ${receive.senderAccountNo}` : ''}
      </div>
      <div style="border-top: 1px dashed #000; margin: 5px 0; padding-top: 5px;">
        <strong>${t('Receiver')}:</strong>
        ${receive.receiverName || 'Unknown'}<br>
        ${receive.receiveAccountNo ? `Acc: ${receive.receiveAccountNo}` : ''}
      </div>    
      <!-- Amount Details -->
      <div style="border-top: 1px dashed #000;">
        <table style="width: 100%; border-collapse: collapse;">
          <tr>
            <td><strong>${t('Amount')}:</strong></td>
            <td style="text-align: right;">${
              formatNumber(receive.receiveAmount) || '0.00'
            }</td>
            <td style="text-align: center;">${
              receive.MainMoneyType?.typeName || 'N/A'
            }</td>
          </tr>
          <tr>
            <td><strong>${t('charges')}:</strong></td>
            <td style="text-align: right;">${
              formatNumber(receive.chargesAmount) || '0.00'
            }</td>
            <td style="text-align: center;">${
              receive.ChargesMoneyType?.typeName || 'N/A'
            }</td>
          </tr>
          <tr style="border-top: 1px solid #000;">
            <td><strong>${t('TOTAL')}:</strong></td>
            <td style="text-align: right; font-weight: bold;">${formatNumber(
              (receive.receiveAmount || 0) + (receive.chargesAmount || 0)
            )}</td>
            <td></td>
          </tr>
        </table>
      </div>

      <!-- Description -->
      ${
        receive.description
          ? `
        <div style="border-top: 1px dashed #000; margin: 5px 0; padding-top: 5px;">
          <strong>${t('Memo')}:</strong>
          ${receive.description}
        </div>
      `
          : ''
      }

      <!-- Footer -->
      <div style="border-top: 1px dashed #000; margin-top: 8px; padding-top: 5px; text-align: center; font-size: 9px;">
        <div>${t('Thank you for banking with us')}</div>
        <div>${new Date().toLocaleDateString()} • ${t('SENDER COPY')}</div>
        <div style="font-size: 8px; margin-top: 3px;">
          ID: TRF-${receive.receiveNo}
        </div>
      </div>

      <!-- Cut here line -->
      <div style="text-align: center; margin-top: 10px; border-top: 1px dashed #000; padding-top: 5px;">
        ✄ - - - - - - - - - - - - - - - - ✄
      </div>
    </div>
  `;
};

export const generateCompactDepositPrintHTML = (deposit, t, formatDisplay) => {
  if (!deposit) return '';

  const customerName =
    deposit.Account?.Customer?.Stakeholder?.Person?.firstName || 'Unknown';
  const currency = deposit.Account?.MoneyType?.typeName || 'N/A';

  return `
    <div style="font-family: 'Courier New', monospace; font-size: 9px; width: 58mm; padding: 3px; line-height: 1.1;">
      <!-- Header -->
      <div style="text-align: center; ">
        <strong>${t('DEPOSIT RECEIPT')}</strong><br>
        <span>#${deposit.No}</span>
      </div>
      <!-- Details -->
      <div style="margin:3px 0px">
        <strong>${t('Customer')}:</strong> ${customerName.substring(0, 15)}<br>
        <strong>${t('Date')}:</strong> ${formatDisplay(
    deposit.DWDate || new Date(),
    {
      showTime: true,
      compact: true,
    }
  )}
      </div>

      <!-- Amount -->
      <div style="border-top: 1px solid #000; border-bottom: 1px solid #000; ">
        <table style="width: 100%;">
          <tr>
            <td>${t('Amount')}:</td>
            <td style="text-align: right; font-weight: bold;">${formatNumber(
              deposit.deposit
            )}</td>
            <td>${currency.substring(0, 3)}</td>
          </tr>
          ${
            deposit.Account?.balance
              ? `
            <tr>
              <td>BALANCE:</td>
              <td style="text-align: right;">${formatNumber(
                deposit.Account.balance
              )}</td>
              <td>${currency.substring(0, 3)}</td>
            </tr>
          `
              : ''
          }
        </table>
      </div>

      ${
        deposit.description
          ? `
        <div style="margin: 4px;  font-size: 8px;">
          <strong>Memo:</strong> ${deposit.description.substring(0, 30)}
        </div>
      `
          : ''
      }

      <!-- Footer -->
      <div style="text-align: center; font-size: 8px;">
        ${new Date().toLocaleDateString()} - CUSTOMER COPY
      </div>

      <div style="text-align: center; margin-top: 5px; font-size: 8px;">
        - - - - - CUT HERE - - - - -
      </div>
    </div>
  `;
};
export const generateCompactWithdrawPrintHTML = (
  withdraw,
  t,
  formatDisplay
) => {
  if (!withdraw) return '';

  const customerName =
    withdraw.Account?.Customer?.Stakeholder?.Person?.firstName || 'Unknown';
  const currency = withdraw.Account?.MoneyType?.typeName || 'N/A';

  return `
    <div style="font-family: 'Courier New', monospace; font-size: 9px; width: 58mm; padding: 3px; line-height: 1.1;">
      <!-- Header -->
      <div style="text-align: center; ">
        <strong>${t('withdraw RECEIPT')}</strong><br>
        <span>#${withdraw.No}</span>
      </div>
      <!-- Details -->
      <div style="margin:3px 0px">
        <strong>${t('Customer')}:</strong> ${customerName.substring(0, 15)}<br>
        <strong>${t('Date')}:</strong> ${formatDisplay(
    withdraw.DWDate || new Date(),
    {
      showTime: true,
      compact: true,
    }
  )}
      </div>

      <!-- Amount -->
      <div style="border-top: 1px solid #000; border-bottom: 1px solid #000; ">
        <table style="width: 100%;">
          <tr>
            <td>${t('Amount')}:</td>
            <td style="text-align: right; font-weight: bold;">${formatNumber(
              withdraw.withdraw
            )}</td>
            <td>${currency.substring(0, 3)}</td>
          </tr>
          ${
            withdraw.Account?.balance
              ? `
            <tr>
              <td>BALANCE:</td>
              <td style="text-align: right;">${formatNumber(
                withdraw.Account.balance
              )}</td>
              <td>${currency.substring(0, 3)}</td>
            </tr>
          `
              : ''
          }
        </table>
      </div>

      ${
        withdraw.description
          ? `
        <div style="margin: 4px;  font-size: 8px;">
          <strong>Memo:</strong> ${withdraw.description.substring(0, 30)}
        </div>
      `
          : ''
      }

      <!-- Footer -->
      <div style="text-align: center; font-size: 8px;">
        ${new Date().toLocaleDateString()} - CUSTOMER COPY
      </div>

      <div style="text-align: center; margin-top: 5px; font-size: 8px;">
        - - - - - CUT HERE - - - - -
      </div>
    </div>
  `;
};
