// utils/printUtils.js
import { formatNumber } from './formatNumber';
import { useDateFormatter } from '../hooks/useDateFormatter';

export const generateTransactionPrintHTML = (
  transactions,
  customerInfo,
  accountSummary,
  t,
  formatDisplay
) => {
  const getTransactionDescription = (transaction) => {
    if (transaction.description) {
      return transaction.description;
    }

    switch (transaction.type) {
      case 'deposit':
        return t('Deposit to account');
      case 'withdraw':
        return t('Withdrawal from account');
      case 'transfer':
        return `${transaction.senderName || t('Sender')} → ${
          transaction.receiverName || t('Receiver')
        }`;
      case 'receive':
        return `${transaction.senderName || t('Sender')} → ${
          transaction.receiverName || t('Receiver')
        }`;
      case 'exchange_sale':
        return t('Currency Sale');
      case 'exchange_purchase':
        return t('Currency Purchase');
      default:
        return t('Transaction');
    }
  };

  return `
    <div class="print-header">
      <h1>${t('Transaction History Report')}</h1>
    </div>

    <div class="print-meta">
      <div>
        <strong>${t('Customer')}:</strong> ${customerInfo.name || 'N/A'}<br>
        <strong>${t('Customer ID')}:</strong> ${customerInfo.id || 'N/A'}
      </div>
      <div style="text-align: right;">
        <strong>${t(
          'Print Date'
        )}:</strong> ${new Date().toLocaleDateString()}<br>
        <strong>${t('Total Transactions')}:</strong> ${transactions.length}
      </div>
    </div>

    ${
      accountSummary.length > 0
        ? `
      <div style="margin-bottom: 20px;">
        <h2 style="margin-bottom: 10px; font-size: 18px;">${t(
          'Account Summary'
        )}</h2>
        <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 10px;">
          ${accountSummary
            .map(
              (account) => `
            <div class="summary-card">
              <strong>${t('Account')} ${account.accountNo}</strong><br>
              <span style="font-size: 16px; font-weight: bold; ${
                account.balance < 0 ? 'color: #dc3545;' : 'color: #28a745;'
              }">
                ${formatNumber(account.balance)} ${account.currency}
              </span>
            </div>
          `
            )
            .join('')}
        </div>
      </div>
    `
        : ''
    }

    ${
      transactions.length > 0
        ? `
      <table>
        <thead>
          <tr>
            <th>${t('Transaction ID')}</th>
            <th>${t('Date & Time')}</th>
            <th>${t('Description')}</th>
            <th class="text-right">${t('Debit')}</th>
            <th class="text-right">${t('Credit')}</th>
            <th class="text-center">${t('Currency')}</th>
            <th class="text-right">${t('Balance')}</th>
            <th class="text-center">${t('Type')}</th>
          </tr>
        </thead>
        <tbody>
          ${transactions
            .map(
              (transaction) => `
            <tr>
              <td>${
                transaction.No ||
                transaction.transferNo ||
                transaction.receiveNo ||
                'N/A'
              }</td>
              <td>${formatDisplay(transaction.date, { showTime: true })}</td>
              <td>${getTransactionDescription(transaction)}</td>
              <td class="text-right">${
                transaction.debit > 0 ? formatNumber(transaction.debit) : '-'
              }</td>
              <td class="text-right">${
                transaction.credit > 0 ? formatNumber(transaction.credit) : '-'
              }</td>
              <td class="text-center">${transaction.moneyType || 'N/A'}</td>
              <td class="text-right ${
                transaction.runningBalance < 0 ? 'negative' : 'positive'
              }">
                ${formatNumber(transaction.runningBalance)}
              </td>
              <td class="text-center">
                ${t(
                  transaction.type === 'exchange_sale'
                    ? 'Exchange Sale'
                    : transaction.type === 'exchange_purchase'
                    ? 'Exchange Purchase'
                    : transaction.type
                )}
              </td>
            </tr>
          `
            )
            .join('')}
        </tbody>
      </table>
    `
        : `
      <div style="text-align: center; padding: 40px; color: #6c757d;">
        <h3>${t('No transactions found')}</h3>
        <p>${t('No transaction records available for printing.')}</p>
      </div>
    `
    }

    <div class="print-footer">
      ${t('Generated by Banking System')} • ${
    window.location.hostname
  } • ${new Date().toLocaleString()}
    </div>
  `;
};
